name: .NET

on:
  release:
    types: [ published ]
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Step 1 - Create a temporary artifact downloads folder
      run: mkdir deploy
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Cloud/Cloud.sln
    - name: Build
      run: dotnet build ./Cloud/Cloud.sln --no-restore
    - name: Deploy
      run: dotnet publish ./Cloud/Cloud.sln -r linux-arm --self-contained false -o deploy
    - name: Copying files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        rm: false
        overwrite: true
        source: "deploy/*"
        target: "${{ secrets.REMOTE_DIR }}"
    - name: Restart cloud
      uses: fifsky/ssh-action@master
      with:
        command: |
          sudo service cloud restart 
        host: ${{ secrets.REMOTE_HOST }}
        user: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
